name: my_imc_calc_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dart_style: ^3.0.1

dependency_overrides:
  analyzer: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.1
  mockito: ^5.4.5
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
