// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTD5uQGe36buMNB5ZOop3uAF6ggxz5mjY',
    appId: '1:763380366761:web:bf50020fbc80dc8a4458b8',
    messagingSenderId: '763380366761',
    projectId: 'firstfirebaseapp-b8a72',
    authDomain: 'firstfirebaseapp-b8a72.firebaseapp.com',
    storageBucket: 'firstfirebaseapp-b8a72.firebasestorage.app',
    measurementId: 'G-NYCX901TG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1BXzi6BZntXoAtP-wk2y6MzUFEiE-wQ',
    appId: '1:763380366761:android:67ed4f6c4ee4d5a64458b8',
    messagingSenderId: '763380366761',
    projectId: 'firstfirebaseapp-b8a72',
    storageBucket: 'firstfirebaseapp-b8a72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEWRROTjXrKrfOFogxTWl4xsEhxOK5PY',
    appId: '1:763380366761:ios:1ba6852998bc844b4458b8',
    messagingSenderId: '763380366761',
    projectId: 'firstfirebaseapp-b8a72',
    storageBucket: 'firstfirebaseapp-b8a72.firebasestorage.app',
    iosBundleId: 'br.com.imc.calc.app.myImcCalcApp',
  );
}
